---
# tasks file for ansible-role-flowdock

  - name: "send a chat message to flowdock"
    flowdock: type=chat 
              external_user_name=ansible_{{ansible_user_id}} 
              msg='ansible successful on {{ ansible_fqdn }} as {{ansible_env["SUDO_USER"]}}' 
              tags='{{ansible_fqdn}}, ansible, ok' 
              token={{flowdock_token}}
    sudo: false
    always_run: yes
    when: flowdock_chat

  - name: 'send a inbox message to flowdock'
    flowdock: type=inbox 
              from_address={{ flowdock_from_address }} 
              link="{{ flowdock_link }}"
              subject="Ansible Run Completed Successfully!" 
              source="ansible" from_name=ansible_{{ansible_user_id}} 
              msg='ansible successful on {{ ansible_fqdn }} as {{ansible_env["SUDO_USER"]}}. IPv4={{ansible_default_ipv4["address"]}}, IPv6={{ansible_default_ipv6["address"]}}, biosdate={{ansible_bios_date}}, biosversion={{ansible_bios_version}}, dist={{ansible_distribution}}, distversion={{ ansible_distribution_version }}, kernel={{ansible_kernel}}, memory={{ ansible_memtotal_mb}}, processor={{ansible_processor[1]}}'
              tags='{{ansible_fqdn}}, ansible, ok, {{ansible_domain}}' 
              token={{flowdock_token}}
    sudo: false
    always_run: yes
    when: not flowdock_chat
